import AltarServerNavbar from "@/components/altar-server-navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AltarServerLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex gap-x-2 flex-row w-full">
        <AltarServerNavbar />
        <main className="ml-[300px] pr-10 py-10 w-full">{children}</main>
      </body>
    </html>
  );
}
