import AdminNavbar from "@/components/admin-navbar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex gap-x-2 flex-row w-full">
        <AdminNavbar />
        <main className="ml-[320px] pr-10 py-10">{children}</main>
      </body>
    </html>
  );
}
